export const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  INVITE: "/invite",
  QR: "/qr",
  SUCCESS: "/success",
  ADMIN: {
    LOGIN: "/admin/login",
    DASHBOARD: "/admin",
    ANALYTICS: "/admin/analytics",
    REGISTRATIONS: "/admin/registrations",
    INVITATIONS: "/admin/invitations",
    EVENTS: "/admin/events",
    BLOG: "/admin/blog",
    SERMONS: "/admin/sermons",
    MINISTRIES: "/admin/ministries",
  },
  PUBLIC: {
    EVENTS: "/events",
    SERMONS: "/sermons",
    BLOG: "/blog",
    MINISTRIES: "/ministries",
    PRAYER: "/prayer",
    CONTACT: "/contact",
  },
};
